name = "ecommerce-platform"
main = "frontend/.open-next/worker.js"
compatibility_date = "2025-09-30"

compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = "frontend/.open-next/assets"
binding = "ASSETS"

# services 要用数组
[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "ecommerce-platform"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cache"

[vars]
NEXT_PUBLIC_API_URL = "https://e-commerce-platform-7zg5.onrender.com"
# CLOUDFLARE_API_TOKEN = "$CLOUDFLARE_API_TOKEN"

