version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    environment:
      - POSTGRES_USER=ecom_user
      - POSTGRES_PASSWORD=ecom_pass
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom_user -d ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: ecommerce_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://ecom_user:ecom_pass@db:5432/ecommerce
    ports:
      - "8000:8000"

volumes:
  pgdata:
